### ISSUE TITLE
doc link is 404

### ISSUE THREAD

**Issue by nexushoratio** [violentmonkey/vm-shortcut#12]
https://violentmonkey.github.io/guide/keyboard-shortcuts/ has a link to https://violentmonkey.github.io/vm-shortcut/ which is currently giving 404.

I thought this was working when I started using this stuff a bit ago.

The similar link for vm-dom IS working:  https://violentmonkey.github.io/vm-dom/

**Comment by gera2ld** [comment]
Yeah I removed it recently since there is a public service at https://www.jsdocs.io/package/@violentmonkey/shortcut
I'll fix the link in the docs soon.
