### ISSUE TITLE
[Bug Report] Unable to Detect Alt Key in MacOS due to `e.key` is used instead of `e.code`

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/vm-shortcut#13]
<img width="1122" alt="Screen Shot 2023-08-26 at 2 46 47" src="https://github.com/violentmonkey/vm-shortcut/assets/44498510/60f538e9-cf15-4d87-9b98-ca34486a75b2">

In MacOS, when pressing `option` key to press a letter, the alternative character will be generated.
For example, `option`+`s` = `ß`
The script shall detect the `keyS` instead of `charCode`.

i.e. in addition to `base: e.key`, which shall be kept as fallback, the `e.code` shall be also passed to the `buildKey` options.
`option` + `keyS` shall be detected and translated to `a-s` for both `KeyCS` and `KeyCI`.

**Comment by cyfung1031** [comment]
@gera2ld   
cc @tophf

**Comment by gera2ld** [comment]
You can check the key expression at https://violentmonkey.github.io/vm-shortcut/ .

**Comment by cyfung1031** [comment]
<img width="795" alt="Screen Shot 2023-09-13 at 0 14 48" src="https://github.com/violentmonkey/vm-shortcut/assets/44498510/6a6e75fb-c49a-482a-a634-a57d06ac8aae">


<img width="802" alt="Screen Shot 2023-09-13 at 0 11 18" src="https://github.com/violentmonkey/vm-shortcut/assets/44498510/b4f01a32-e7aa-40de-b809-a1352ef85d68">

<img width="789" alt="Screen Shot 2023-09-13 at 0 12 26" src="https://github.com/violentmonkey/vm-shortcut/assets/44498510/b44c5fbd-bfd9-4750-92ff-ce7a573486fb">


For alphabets and numbers, `key` is the same as `code`.
For symbols like `! : , [ > "`, key is not the same as the code.

But I think this is acceptable as we can use `a-keya` (code) to register the shortcut.

Thanks

**Comment by cyfung1031** [comment]
@gera2ld  Unable to detect <img width="54" alt="Screen Shot 2023-09-13 at 0 44 37" src="https://github.com/violentmonkey/vm-shortcut/assets/44498510/fe15078e-93fd-489c-9aeb-f01b71ce012e"> key. Both code and key not working

<img width="803" alt="Screen Shot 2023-09-13 at 0 41 35" src="https://github.com/violentmonkey/vm-shortcut/assets/44498510/11608131-8c33-4b58-bb47-b3de73f245df">


And I found that this is the only key which is different with other keys.

for key, other are just characters, even they are alternative characters.
but for this one, it is a text "dead"

**Comment by gera2ld** [comment]
If it doesn't show in the page, it means it's blocked by the browser.
This library can only handle keys that can be captured.

For me ``c-` ``/`c-s-~` both works, but ``a-` `` is occupied by the browser/system.

**Comment by cyfung1031** [comment]
> If it doesn't show in the page, it means it's blocked by the browser. This library can only handle keys that can be captured.
> 
> For me `c-~`/`c-s-~` both works, but `a-~` is occupied by the browser/system.
<img width="782" alt="Screen Shot 2023-09-13 at 0 48 45" src="https://github.com/violentmonkey/vm-shortcut/assets/44498510/2028d5a8-2e52-4b9b-a5c7-1702caed9388">

For macOS, `control` + "\`" is "c-\`", but `option` + "\`" is "a-dead"

**Comment by gera2ld** [comment]
That means `e.key` is `dead` while `e.code` is `backquote`. Both are supported. Maybe I should add both to the example code.

**Comment by gera2ld** [comment]
I just tried on macOS, both `a-dead` and `a-backquote` worked.
![image](https://github.com/violentmonkey/vm-shortcut/assets/3139113/9e7d5b96-0fc8-4532-808c-8d33a14d6021)
![image](https://github.com/violentmonkey/vm-shortcut/assets/3139113/3f15dca2-52e1-4758-90ca-a486842c6b46)


If you still have issues, please elaborate what is expected and what is the actual result.

**Comment by cyfung1031** [comment]
tried again and it works now. It might be just a bug in the testing tool of the previous version.

Anyway, thanks for the update.

**Comment by fuzy112** [comment]
It seems that fixing this caused a new bug #14
