### ISSUE TITLE
Might add `cm` as abbr. to `ctrlcmd`

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/vm-shortcut#17]
```
Possible modifiers are:

c, ctrl, control
s, shift
a, alt
m, meta, cmd
ctrlcmd
```

Since ctrl is `c` and cmd is `m`, `cm` shall be added to represent `ctrlcmd`
also `ctrlmeta` might be?

**Comment by gera2ld** [comment]
Sounds reasonable. Would you like a PR?
BTW `ctrlcmd` follows VSCode, I don't want `ctrlmeta` since it's not commonly used.
