### ISSUE TITLE
能否作为函数被动调用

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/vm-shortcut#3]
现在都是需要用户主动按键来实现，能否实现被动调用，即达成某条件时调用快捷键，如：
```
windown.onload = () => {
	VM.Shortcut('c-i');
}

```

**Comment by gera2ld** [comment]
直接调用注册的那个方法不好吗？你是想模拟键盘操作？

**Comment by ivysrono** [comment]
对，我想模拟键盘操作。
顺便一问，一个情形：alert 阻塞了所有 js 的继续执行，那 alert 后模拟 回车键 或 刷新页面 能做到么？

**Comment by gera2ld** [comment]
> 一个情形：alert 阻塞了所有 js 的继续执行，那 alert 后模拟 回车键 或 刷新页面 能做到么？

不能，一般的做法是把浏览器的alert劫持掉，换成HTML实现

**Comment by gera2ld** [comment]
这个库是用来注册快捷键的，不支持模拟键盘操作
