### ISSUE TITLE
Export the `isInput` function.

### ISSUE THREAD

**Issue by nexushoratio** [violentmonkey/vm-shortcut#9]
Followup to #6 

The docs for VM.shortcut mentions the `isInput` function and in #6, a pointer was given to it in the code.

While it is a simple function and easy to implement, it would be a nice addition to have it exposed via the VM.shortcut API.

```
$ wget -q -O - https://cdn.jsdelivr.net/npm/@violentmonkey/shortcut@1 | grep -o -e register -e isInput
register
register
register
register
register
register
```

Using VM as my userscript manager, it does not appear to be exposed there either, though, if I'm reading the code correctly, it is used internally to VM for its own UI?

**Comment by gera2ld** [comment]
`isInput` is just an example, it has nothing to do with this library.
